In [4]:
# np.repeat(value, times)
np.repeat(2,10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
import numpy as np
array1  = np.arange(0,10).reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
np.repeat(2,10).reshape(2,-1)
# np.full((2,5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [6]:
np.full((2,5),12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [7]:
np.arange(0,6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
np.arange(3,7).reshape(2,2)

array([[3, 4],
       [5, 6]])

In [9]:
np.arange(7,11).reshape(2,2)

array([[ 7,  8],
       [ 9, 10]])

In [6]:
k = np.random.randint(1,25,15).reshape(5,3)
m= k.flatten()
display(k,m)

array([[13,  2,  7],
       [ 7, 13,  7],
       [ 3, 10, 24],
       [20,  3, 18],
       [ 3,  5,  3]])

array([13,  2,  7,  7, 13,  7,  3, 10, 24, 20,  3, 18,  3,  5,  3])

In [8]:
# uniq = np.unique(k)
# caunt = np.unique(k, return_counts = True)
# caunt

uniq, caunt = np.unique(k,return_counts = True)
display(uniq, caunt)

array([ 2,  3,  5,  7, 10, 13, 18, 20, 24])

array([1, 4, 1, 3, 1, 2, 1, 1, 1], dtype=int64)

In [9]:
list(zip(uniq, caunt))    

[(2, 1), (3, 4), (5, 1), (7, 3), (10, 1), (13, 2), (18, 1), (20, 1), (24, 1)]

In [20]:
np.argmax(uniq)

10

In [3]:
np.__version__

'1.18.1'

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a.itemsize

8

In [30]:
# np.info(np.linspace)
np.linspace(2.0, 3.0,  3)

array([2. , 2.5, 3. ])

In [32]:
ar = np.zeros(10)
ar[4] = 1
ar

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [36]:
arr = np.arange(10,50)

In [37]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [39]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
ar1 = [1,2,0,0,4,0]
np.nonzero(ar1)

(array([0, 1, 4], dtype=int64),)

In [47]:
np.ones((3,3), dtype = int)
np.eye(3)
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [5]:
np.random.random((3,3,3))

array([[[0.22442662, 0.82840427, 0.77927542],
        [0.69523066, 0.70719345, 0.82441519],
        [0.2933019 , 0.88486628, 0.32866167]],

       [[0.53985867, 0.20285823, 0.81267726],
        [0.14607174, 0.00381104, 0.20632474],
        [0.88791071, 0.0382341 , 0.85057552]],

       [[0.84668149, 0.53379296, 0.92593295],
        [0.1787083 , 0.84200355, 0.70739492],
        [0.97785334, 0.30958289, 0.66739992]]])

In [59]:
z =np.random.random((10,10))
zmin, zmax = z.min(), z.max()
display(zmin, zmax)

0.0012885982152536224

0.9992514164389432

In [7]:
z=np.random.random(30)
print(z)
z.mean()

[0.4602444  0.2188429  0.28743589 0.67671671 0.73534006 0.45600308
 0.10032017 0.88085209 0.57934552 0.69229308 0.13345321 0.32164527
 0.36709532 0.28805955 0.52208942 0.07282938 0.27625961 0.98050353
 0.19045192 0.41160352 0.65593385 0.37576738 0.56274295 0.17238614
 0.48528213 0.86772951 0.24474609 0.84074811 0.36187675 0.29821995]


0.4505605823892723

In [71]:
Z = np.ones((5,5))

Z[:, [0, -1]] = 0

Z[[0, -1], :] = 0

print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [72]:
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


0.30000000000000004