In [2]:
import numpy as np

In [36]:
arr1 = np.array([
    [1,2,3,4],
    [11,22,33,44],
    [101,102, 103,104]
])
print(arr1)

# arr2 = arr1[1:3, 1:3]
# print(arr2)

[[  1   2   3   4]
 [ 11  22  33  44]
 [101 102 103 104]]


In [19]:
arr2 = np.array(arr1[:2, 1:3])
# made copy of arr1 so that both remain independent

In [20]:
arr2[1,1] = 99
print(arr1, '\n',arr2) # VALUES CHANGED IN ARR1 ALSO

[[  1   2   3   4]
 [ 11  22  33  44]
 [101 102 103 104]] 
 [[ 2  3]
 [22 99]]


In [26]:
# integer indexing and slice indexing, obselete
print('values',arr1[1, :], '\n', 'rank', arr1.shape)

values [11 22 33 44] 
 rank (3, 4)


In [37]:
arr1 =arr1.T

In [38]:
arr1

array([[  1,  11, 101],
       [  2,  22, 102],
       [  3,  33, 103],
       [  4,  44, 104]])

In [54]:
col = np.array([0,1,2,2])
row = np.arange(4)
print(zip(row,col))

for row, col in zip(row,col):
    print(row, col)

In [55]:
arr1[row,col]

array([  1,  22, 103, 104])

In [58]:
arr1[row,col] += 1000000000
arr1

array([[1000020001,      10011,      10101],
       [     10002, 1000020022,      10102],
       [     10003,      10033, 1000020103],
       [     10004,      10044, 1000020104]])

In [2]:
# boolean indexing
ar = np.arange(6).reshape(3,2)
ar

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
ar>3

array([[False, False],
       [False, False],
       [ True,  True]])

In [63]:
fltr = ar>3

In [64]:
ar[fltr]

array([4, 5])

In [72]:
ar[ar>3]

array([100, 102, 104,   5])

In [71]:
ar[(ar>2) & (ar<100)]

array([3, 5])

In [69]:
# change the values based on condition
ar[(ar%2 == 0)]+=100
ar

array([[100,   1],
       [102,   3],
       [104,   5]])

In [3]:
g = [1,2,3,4]
print(type(g))

g1 = np.array(g)
print(g1,type(g1))
s = g1+10
print(s)

<class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>
[11 12 13 14]


In [2]:
# np.array(range(0,101))
np.array([i for i in range(0,101)])/5
# s = np.array([i for i in range(0,101)])/5
# print(s/5)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

In [5]:
# count no of brackets for knowing the dimensions
a = np.array([
            [1,2,3],
            [2,3,4],
            [5,6,7]
            ])
display(print(a),
np.shape(a),
type(a),
a.size,
a.dtype,
a.ndim,
a.itemsize,
np.unique(a))
# Size: The total number of elements in an array
# Shape: The shape of an array
# Dimension: The dimension or rank of an array
# Dtype: Data type of an array
# Itemsize: Size of each element of an array in bytes
# Nbytes: Total size of an array in bytes
# argwhere:returns index number    
# unique: gives o/p in array to give unique elemnents    

[[1 2 3]
 [2 3 4]
 [5 6 7]]


None

(3, 3)

numpy.ndarray

9

dtype('int32')

2

4

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
np.shape(a)

(3, 3)

In [12]:
s = np.random.rand(2,3)   #b/w 0-1
print(s)

[[0.83845114 0.92235064 0.512663  ]
 [0.97094484 0.46032677 0.58337948]]


In [7]:
print(np.random.randint(1,50))
print(np.random.randint(1,50,10))

49
[ 2  1 32  9 38 14 31 39  5 25]


In [15]:
s = np.random.randint(0,20,5)
print(s)
# np.unique(s)

[ 9 18  8 13  0]


In [8]:
a.mean()
a.std() # std deviation
np.sum(a)
np.median(a)

3.0

In [11]:
np.round(np.median(a),2)

3.0

In [16]:
# reshape array in another dimension

l = np.array(range(0,100))

l1 = l.reshape(25,4)
# display('l = ',l, 'l1 = ',l1)
# print('l-shape',l.shape, 'l1-shape',l1.shape)

l2 = l1.flatten()
l2.size

100

In [14]:
l = np.array(range(1,26))
print(l)
l1 = l.reshape(5,5)
l1.shape
l1.size

l2 = l.flatten()
display(l1.shape, l2.shape)
l2.sum()

np.random.rand(1,26)  

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


(5, 5)

(25,)

array([[0.75904543, 0.23324682, 0.05696425, 0.53774866, 0.5702994 ,
        0.92379618, 0.07356696, 0.59039597, 0.39457165, 0.80069885,
        0.88049745, 0.46799284, 0.50098451, 0.91866154, 0.0048421 ,
        0.5241165 , 0.51713153, 0.15271193, 0.11690263, 0.35191126,
        0.51929705, 0.40320322, 0.58746684, 0.283029  , 0.89931322,
        0.42687963]])

In [47]:
np.random.rand(10)    # positive values
np.random.randn(10)   # negative value

array([ 1.46305108, -0.30495395,  0.0820125 ,  0.10196616, -1.86310525,
        0.88373815,  1.6847445 ,  0.88805768, -1.36127995, -0.09447103])

In [16]:
l2 = np.array([[1,2],
               [5,6],
               [7,8]    
            ])
f = np.argwhere(l2>5)
f

array([[1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

In [17]:
arr = np.array((1,2,3,7,4,5,6))
print(arr*2)
print(arr.dtype)
arr
type(arr)


[ 2  4  6 14  8 10 12]
int32


numpy.ndarray

In [18]:
# if one data type is of string,float,int then whole array seems to be of that datatype itself
array1 = np.array((1,2,3,4,'k', 4.5))
array1

array(['1', '2', '3', '4', 'k', '4.5'], dtype='<U11')

In [9]:
arr1 = ([1,2,2],[2,3,3],[4,3,4])
np.unique(arr1)
np.unique(arr1, return_counts = True)   # return_counts -> occ of each element

(array([1, 2, 3, 4]), array([1, 3, 3, 2], dtype=int64))

In [23]:
np.random.randint(1,26,2)

array([7, 5])

In [25]:
np.random.seed(2000)  # seed for getting same values each times
np.random.randint(1,25,16).reshape(4,4)[:2, 1:3]  # (row, col)
# np.random.randint(1,25,16).reshape(4,4)[2:,2:]

array([[ 9, 15],
       [ 5, 19]])

In [33]:
np.random.seed(2000)
print(np.random.randint(1,25,15).reshape(5,-1))

# custom selection
# np.random.randint(1,25,15).reshape(5,-1)[[1,2,4], [1,0,2]]

a = np.random.randint(1,25,15).reshape(5,-1)#[[0,0,1,1,3,4,4], [1,2,1,2,1,0,1]]
a[[0,0,1,1,3,4,4], [1,2,1,2,1,0,1]]

[[23  9 15]
 [14 23  5]
 [19 24 15]
 [ 5 16  3]
 [12  2 15]]


array([24,  8,  1, 11,  5, 15,  1])

In [11]:
ar = np.random.randint(0,10,5)
display(ar, sorted(ar),  np.unique(ar),  np.sort(ar))

array([0, 5, 8, 2, 0])

[0, 0, 2, 5, 8]

array([0, 2, 5, 8])

array([0, 0, 2, 5, 8])

In [ ]:
np.random.randint

In [31]:
# arange(start, stop, step-size)
np.arange(0.1,11.1,2)


array([ 0.1,  2.1,  4.1,  6.1,  8.1, 10.1])

In [34]:
for i in np.arange(0.1, 11.1, 2):
    print(i)
    
np.array([i for i in np.arange(0.1, 11.1,2)])    

0.1
2.1
4.1
6.1
8.1
10.1


array([ 0.1,  2.1,  4.1,  6.1,  8.1, 10.1])

In [38]:
20%2

0

In [35]:
k = np.arange(0,30,5).reshape(3,2)%2 # dinominator
k

array([[ 0,  5],
       [10, 15],
       [20, 25]])

In [5]:
a1 = np.arange(0.1, 10.1)
a2 = np.arange(1.1, 11.1)
display(a1+a2)
# same shape is required else error

array([ 1.2,  3.2,  5.2,  7.2,  9.2, 11.2, 13.2, 15.2, 17.2, 19.2])

In [3]:
a = np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
# zeros and ones
# give 0's and 1's at the place in the matix
display(np.ones((3,4)),
np.ones((2,3))*5)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[5., 5., 5.],
       [5., 5., 5.]])

In [46]:
np.zeros((5,2))
np.zeros((2,2))*2

array([[0., 0.],
       [0., 0.]])

In [41]:
# linspace(start,stop,num = 50)
# evenly spaced values
# gives 1-D array
display(np.linspace(0,20,10),
np.linspace(0,20,3),
np.linspace(0,20,10).reshape(5,2))

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

array([ 0., 10., 20.])

array([[ 0.        ,  2.22222222],
       [ 4.44444444,  6.66666667],
       [ 8.88888889, 11.11111111],
       [13.33333333, 15.55555556],
       [17.77777778, 20.        ]])

In [52]:
np.linspace(0,10,6).reshape(2,3).flatten()

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [55]:
# astype
np.linspace(0,20).astype(int)
np.linspace(0,10).astype(str)

array(['0.0', '0.20408163265306123', '0.40816326530612246',
       '0.6122448979591837', '0.8163265306122449', '1.0204081632653061',
       '1.2244897959183674', '1.4285714285714286', '1.6326530612244898',
       '1.836734693877551', '2.0408163265306123', '2.2448979591836737',
       '2.4489795918367347', '2.6530612244897958', '2.857142857142857',
       '3.0612244897959187', '3.2653061224489797', '3.4693877551020407',
       '3.673469387755102', '3.8775510204081636', '4.081632653061225',
       '4.285714285714286', '4.4897959183673475', '4.6938775510204085',
       '4.8979591836734695', '5.1020408163265305', '5.3061224489795915',
       '5.510204081632653', '5.714285714285714', '5.918367346938775',
       '6.122448979591837', '6.326530612244898', '6.530612244897959',
       '6.73469387755102', '6.938775510204081', '7.142857142857143',
       '7.346938775510204', '7.551020408163265', '7.755102040816327',
       '7.959183673469388', '8.16326530612245', '8.36734693877551',
       '8.5714

In [58]:
# eye
# 2-D array
display(np.eye(3, 3), np.eye(3, 3, -1), np.eye(3, 3, +1))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [62]:
# transpose
arr = np.arange(10).reshape(5,2)
display(arr, arr.T)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [66]:
# Full
# np.full(shape, fill_value)
display((np.zeros(3)+6).astype(int),
       np.full(3,6),
       np.full((3,3),6)
       )

array([6, 6, 6])

array([6, 6, 6])

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [69]:
# max and min values in an array
arr = np.arange(0.5, 10.5)
ar = np.argmax(arr)
a1 = np.argmin(arr)
display(arr, ar, a1)

# gettin row and cols
# h = arr.reshape(2,-1)
# np.argwhere(h == h.max())

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

9

0

In [73]:
# Broadcasting
akr = np.arange(0.1, 10.1)
akr[:] = 9
akr

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [76]:
# update value
akr[0] = 10
akr[0:2] = '200'
print(akr)
print(akr.dtype)

[200. 200.   9.   9.   9.   9.   9.   9.   9.   9.]
float64


In [44]:
# fancy indexing
# allows to select entire rows and col out of order

# set up matrix
arr1 = np.arange(100).reshape(10,10)
arr2 =  np.arange(100).reshape(10,10)[[4,1,8]]
arr3 =  np.arange(100).reshape(10,10)[: ,[4,1,8]]
display(arr1, arr2, arr3)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

array([[ 4,  1,  8],
       [14, 11, 18],
       [24, 21, 28],
       [34, 31, 38],
       [44, 41, 48],
       [54, 51, 58],
       [64, 61, 68],
       [74, 71, 78],
       [84, 81, 88],
       [94, 91, 98]])

In [88]:
bool_arr = arr1>40
bool_arr.astype(int)

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [89]:
# return where values are true only
arr1[arr1>40]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
import numpy as np
array1 = np.arange(1,11).reshape(-1,2)
cumulative_product = np.cumprod(array1)
cum_sum = np.cumsum(array1)
display(array1, cumulative_product, cum_sum)
array1.flatten()
np.cumsum(array1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [5]:
array1+array1
array1-array1
array1*array1

array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100]])

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
h = np.array([0,1,2])
h/0
#blank == NaN 

array([nan, inf, inf])

In [8]:
# also warning but an error instead infinity
1/array1

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ],
       [0.11111111, 0.1       ]])

In [11]:
# Universal Array Functions
np.random.seed(20)
arr = np.random.randint(0,11,10)
np.sqrt(arr)
arr

array([ 3, 10, 10,  9,  4,  6,  7,  2,  0,  6])

In [10]:
# calculating product
np.prod(arr)

0

In [18]:
np.mean(arr)
np.round(2.34356,2)
a = 2.343
int(np.round(a,0))  # or
np.round(a,0).astype(int)

2

In [26]:
s = np.std(arr)
a = np.around(6.54)  #like ceil and floor
ab =np.abs(-89)
ab1 = np.absolute(-89)
pr = np.cumprod(arr)   # or cumproduct
su = np.cumsum(arr)
ma = np.argmax(arr)
sq = np.square(arr)
po = np.power(arr,3)
sin1 = np.sin(arr)
log1 = np.log10(arr) # or natural log(np.log(arr))
display(arr,s,a,ab,ab1,pr,su,ma,sq,po,sin1,log1)

array([ 3, 10, 10,  9,  4,  6,  7,  2,  0,  6])

3.257299494980466

7.0

89

89

array([     3,     30,    300,   2700,  10800,  64800, 453600, 907200,
            0,      0], dtype=int32)

array([ 3, 13, 23, 32, 36, 42, 49, 51, 51, 57], dtype=int32)

1

array([  9, 100, 100,  81,  16,  36,  49,   4,   0,  36], dtype=int32)

array([  27, 1000, 1000,  729,   64,  216,  343,    8,    0,  216],
      dtype=int32)

array([ 0.14112001, -0.54402111, -0.54402111,  0.41211849, -0.7568025 ,
       -0.2794155 ,  0.6569866 ,  0.90929743,  0.        , -0.2794155 ])

array([0.47712125, 1.        , 1.        , 0.95424251, 0.60205999,
       0.77815125, 0.84509804, 0.30103   ,       -inf, 0.77815125])

In [27]:
arr1 = [9,8,7,6]
arr2 = [1,2,3,4]
np.power(arr1, arr2)

array([   9,   64,  343, 1296], dtype=int32)

In [46]:
def fn(string):
    temp = set(string)
    if len(temp) != len(string):
        return 'yes duplicate'
    else:
        return 'not dups!!'
fn('helo')            

'not dups!!'

In [48]:
def double_letters(a):
    l= [i.split(' ') for i in a]
    for x in l:
        if l.count(x) > 1:
            return True
    return False

double_letters(input())



hello


True

In [49]:
list1 = ['k', 'o', 'm','a', 'l']
list1.count('k')

1

## ndarray operations and datatypes

In [6]:
ex1 = np.array([11,12])
ex2 = np.array([11.2,12.7])
display(ex1.dtype, ex2.dtype)



dtype('int32')

dtype('float64')

In [8]:
ex3 = np.array([11.2, 12.9], dtype = np.int64)
print(ex3.dtype)
ex3

int64


array([11, 12], dtype=int64)

In [10]:
# datatypes matter in ndarray
ex4 = np.array([11,12], dtype = np.float64)
print(ex4, ex4.dtype)

[11. 12.] float64


### add, subtract,multiply, divide, sqrt, exp

In [21]:
ex0 = np.array([[11.0,12.4], [13.5, 14.4]])
ex1 = np.arange(11,15).reshape(2,2)
print('add', ex0+ex1)
print('sub', np.subtract(ex0,ex1))
print('mul', np.multiply(ex0,ex1))
print('div', np.divide(ex0,ex1))
print('sqrt', np.sqrt(ex0))
print('exp', np.exp(ex0))


add [[22.  24.4]
 [26.5 28.4]]
sub [[0.  0.4]
 [0.5 0.4]]
mul [[121.  148.8]
 [175.5 201.6]]
div [[1.         1.03333333]
 [1.03846154 1.02857143]]
sqrt [[3.31662479 3.52136337]
 [3.67423461 3.79473319]]
exp [[  59874.1417152   242801.61749832]
 [ 729416.3698477  1794074.77260621]]


### statistical, sorting, set operations

In [5]:
ar = 10* np.random.randn(2,5) # standard normal distribution
ar

array([[  5.03548146, -15.83386208, -12.79726826,  -7.20606249,
         -4.43459028],
       [ 16.40796756,   2.97279347,   3.3400195 ,  11.21243934,
         -6.20919388]])

In [3]:
np.random.rand()

0.05539885263540034

In [6]:
# mean by row*col
print(ar.mean(axis = 1))
print(ar.mean(axis = 0))

[-7.04726033  5.5448052 ]
[10.72172451 -6.4305343  -4.72862438  2.00318843 -5.32189208]


In [7]:
# median
np.median(ar, axis = 0)

array([10.72172451, -6.4305343 , -4.72862438,  2.00318843, -5.32189208])

In [11]:
ar = np.random.rand(10)
ar

array([0.11493051, 0.95401271, 0.57179569, 0.12194161, 0.00967684,
       0.70530674, 0.63042681, 0.27962474, 0.08546346, 0.19578357])

In [14]:
ar.sort()
ar

array([0.00967684, 0.08546346, 0.11493051, 0.12194161, 0.19578357,
       0.27962474, 0.57179569, 0.63042681, 0.70530674, 0.95401271])

In [15]:
sorted(ar)

[0.00967683935848751,
 0.08546346211380118,
 0.11493051106770891,
 0.12194161408247806,
 0.19578356793884333,
 0.2796247434111211,
 0.5717956935045105,
 0.6304268087649502,
 0.7053067381392738,
 0.9540127087299811]

In [19]:
a = np.array(['cake', 'pie','carrot'])
b = np.array(['carrot', 'pie', 'beans'])

In [20]:
np.intersect1d(a,b) # common

array(['carrot', 'pie'], dtype='<U6')

In [21]:
np.union1d(a,b) # unique

array(['beans', 'cake', 'carrot', 'pie'], dtype='<U6')

In [22]:
np.setdiff1d(a,b) # a-b

array(['cake'], dtype='<U6')

In [23]:
np.in1d(a,b) # cake is not in both 

array([False,  True,  True])

In [26]:
# broadcasting
a = np.array([[0,0], [0,0]])
b1 = np.array([1,1])
b2 = 1
a+b2, a+b1

array([[1, 1],
       [1, 1]])

In [ ]:
# speed test ndarray and list
